"""Update organization cascade

Revision ID: 1c5b0e54729a
Revises: f4a1a9c2d18e
Create Date: 2026-04-22 12:03:25.214505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c5b0e54729a'
down_revision: Union[str, Sequence[str], None] = 'f4a1a9c2d18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ORGANIZATIONS_CREATED_BY_FK = 'organizations_created_by_id_fkey'


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f(ORGANIZATIONS_CREATED_BY_FK), 'organizations', type_='foreignkey')
    op.create_foreign_key(
        ORGANIZATIONS_CREATED_BY_FK,
        'organizations',
        'users',
        ['created_by_id'],
        ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f(ORGANIZATIONS_CREATED_BY_FK), 'organizations', type_='foreignkey')
    op.create_foreign_key(
        ORGANIZATIONS_CREATED_BY_FK,
        'organizations',
        'users',
        ['created_by_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###
