"""add_people_needed_to_task

Revision ID: 7fb541e05c99
Revises: 1c5b0e54729a
Create Date: 2026-04-25 00:44:36.091866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb541e05c99'
down_revision: Union[str, Sequence[str], None] = '1c5b0e54729a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('people_needed', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'people_needed')
    # ### end Alembic commands ###
